# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-19 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='网站'),
        ),
    ]
